name: "Delete infra daily"
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  delete:
    runs-on: ubuntu-latest
    concurrency: terraform-operation
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v3
        with:
          go-version-file: "backend/go.mod"
          cache: true
          cache-dependency-path: backend/go.sum

      - uses: actions/setup-node@v3
        with:
          node-version: "18.4.0"
          cache: "yarn"
          cache-dependency-path: front/yarn.lock

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
