name: "Delete infra daily"
on:
  schedule:
    - cron: "0 20 * * *"

jobs:
  delete:
    runs-on: ubuntu-latest
    concurrency: terraform-operation
    steps:
      - uses: actions/checkout@v2


      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Delete
        run: terraform apply -auto-approve -input=false
