name: "Build, test and deploy"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-go@v3
        with:
          go-version-file: "backend/go.mod"
          cache: true
          cache-dependency-path: backend/go.sum
        
      - name: "Install dependencies"
        run: |
          go get -v .
        working-directory: backend
      
      - name: "Test"
        run: |
          go test -v .
        working-directory: backend
      
      - name: "Build"
        run: |
          go build .
        working-directory: backend
      
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "api"
          path: ./backend/api