name: "Build, test and deploy"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      
      - name: "Test"
        run: |
          go test -v ./...
        working-directory: backend
      
      - name: "Build"
        run: |
          go build .
        working-directory: backend
      
      - name: "Upload artifact"
        uses: actions/artifact@v2
        with:
          name: "api"
          path: ./backend/api