name: "Build, test and deploy"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: 
  contents: read
  pages: write
  id-token: write

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-go@v3
        with:
          go-version-file: "backend/go.mod"
          cache: true
          cache-dependency-path: backend/go.sum
        
      - name: "Install dependencies"
        run: |
          go get -v .
        working-directory: backend
      
      - name: "Test"
        run: |
          go test -v .
        working-directory: backend
      
      - name: "Build"
        run: |
          go build .
        working-directory: backend
      
      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "api"
          path: ./backend/api
  
  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-node@v3
        with:
          node-version: "18.4.0"
          cache: "yarn"
          cache-dependency-path: front/yarn.lock
      - run: yarn
        working-directory: front
      - run: yarn build
        working-directory: front
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./front/dist/
  
  deploy-front:
    runs-on: ubuntu-latest
    needs:  build-front
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@latest
    
    
