name: "Delete infra daily"
on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    concurrency: terraform-operation
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN }}

      - run: terraform init
      - name: Prepare dummy files
        run: |
          mkdir front/dist
          touch front/dist/index.html
          touch backend/cmd/lambda/app
      - run: terraform destroy -auto-approve -input=false
      - name: Notify failure to slack
        if: failure()
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: ${{ secrets.SLACK_NOTIFY_CHANNEL }}
          status: Failed
          color: danger
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
